-- TEXTURES
system.loadTexture("textures/teleporterBeamGlow.png")
system.loadTexture("textures/fireExplosionGlow.png")
system.loadTexture("textures/charger_enemy_shadow.png")
system.loadTexture("textures/vignetteShadow.png")
system.loadTexture("textures/teleporterGlow.png")
system.loadTexture("textures/bkg_stars_distant.png")
system.loadTexture("textures/introLevelMask.png")
system.loadTexture("textures/powerupSheet.png")
system.loadTexture("textures/whiteFloorGlow.png")
system.loadTexture("textures/gameObjects.png")
system.loadTexture("textures/blueFloorGlow.png")
system.loadTexture("textures/bkg_stars.png")
system.loadTexture("textures/vignetteMask.png")
system.loadTexture("textures/introLevel.png")
system.loadTexture("textures/redFloorGlow.png")
system.loadTexture("textures/lampLight.png")
system.loadTexture("textures/introWall.png")
system.loadTexture("textures/bkg_orbit2.png")

-- SOUNDS
system.loadSound("sounds/laser.ogg")
system.loadSound("sounds/gunshot.ogg")
system.loadSound("sounds/creak.ogg")
system.loadSound("sounds/bite-small.wav")
system.loadSound("sounds/bite-small3.wav")
system.loadSound("sounds/woosh.ogg")
system.loadSound("sounds/wooshMono.ogg")
system.loadSound("sounds/espark.ogg")
system.loadSound("sounds/silenced.ogg")
system.loadSound("sounds/laser.ogg")
system.loadSound("sounds/blast1.ogg")
system.loadSound("sounds/electricHum.ogg")
system.loadSound("sounds/footstepDirt1.ogg")
system.loadSound("sounds/footstepDirt2.ogg")
system.loadSound("sounds/footstepDirt3.ogg")
system.loadSound("sounds/footstepDirt4.ogg")
system.loadSound("sounds/footstepDirt5.ogg")
